### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by himansh123** [jfilter/split-folders#3]
I get the following error, at this line : split_folders.ratio('non_dup', output="data_", seed=42, ratio=(.8, .2))

`
Traceback (most recent call last):
  File "image_classification_2.py", line 53, in <module>
    split_folders.ratio('non_dup', output="data_", seed=42, ratio=(.8, .2))
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/split_folders/split.py", line 58, in ratio
    split_class_dir_ratio(class_dir, output, ratio, seed)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/split_folders/split.py", line 126, in split_class_dir_ratio
    copy_files(li, class_dir, output)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/split_folders/split.py", line 148, in copy_files
    class_name = path.split(class_dir)[1]
  File "/home/ubuntu/anaconda3/lib/python3.5/posixpath.py", line 103, in split
    i = p.rfind(sep) + 1
AttributeError: 'PosixPath' object has no attribute 'rfind'
`

**Comment by jfilter** [comment]
See #2.
